version: '3'  # 도커 컴포즈 파일의 버전
services:  # 애플리케이션의 서비스 정의

  workout-archive-db: # 서비스 이름
    image: gillilo/workout-archive-db:latest  # 사용할 도커 이미지
    container_name: workout-archive-db  # 컨테이너 이름
    volumes:
      - workout-archive-data:/var/lib/postgresql/data
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 256M
    restart: on-failure  # 재시작 정책

  workout-archive-api:
    image: gillilo/workout-archive-api:latest
    container_name: workout-archive-api
    environment:  # 환경 변수 설정
      - DB_URL=workout-archive-db
      - DB_PORT=5432
      - DB_NAME=workoutArchive
      - DB_USERNAME=gillilo
      - DB_PASSWORD=gillilo
    ports:  # 포트 매핑
      - 83:80
    depends_on:
      - workout-archive-db
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.5'
    #       memory: 512M
    restart: on-failure

  workout-archive-web:
    image: gillilo/workout-archive-web:latest
    container_name: workout-archive-web
    environment:  # 환경 변수 설정
      - REQUEST_URL=http://workout-archive-api
    ports:  # 포트 매핑
      - 84:80
    # depends_on:
    #   - workout-archive-api
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.5'
    #       memory: 512M
    restart: on-failure

networks:  # 네트워크 정의
  workout-archive:
    driver: bridge  # 네트워크 드라이버

volumes:  # 볼륨 정의
  workout-archive-data:
    driver: local  # 볼륨 드라이버

